"""
app/services/etl/profiler.py

Heuristic-based column profiling performed locally before AI schema detection.

Responsibilities:
  - Infer column data types (numeric, date, categorical, text)
  - Compute descriptive statistics per column
  - Identify candidate dimension and measure columns
  - Build the sample payload sent to the AI Schema Agent (RF-02)

Running heuristics first reduces token usage and provides a fallback
when the AI provider is unavailable (RNF-04).
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Optional

import numpy as np
import pandas as pd

from app.core.logging import get_logger

logger = get_logger(__name__)

# Columns with fewer unique values than this ratio are treated as categorical
CATEGORICAL_CARDINALITY_RATIO = 0.10
# Minimum share of parseable values to declare a column numeric or date
TYPE_CONFIDENCE_THRESHOLD = 0.80


@dataclass
class ColumnProfile:
    """Metadata inferred for a single column."""

    name: str
    inferred_type: str          # "numeric" | "date" | "categorical" | "text"
    alias: str = ""             # human-readable name (filled by AI agent)
    sample_values: list[Any] = field(default_factory=list)
    null_rate: float = 0.0
    unique_count: int = 0
    stats: dict[str, Any] = field(default_factory=dict)
    suggested_role: str = ""    # "dimension" | "measure" | "datetime" | "label"


@dataclass
class DatasetProfile:
    """Aggregated profile of the entire dataset."""

    row_count: int
    column_count: int
    columns: list[ColumnProfile]
    # Human-readable description of the dataset (generated by AI or heuristic)
    dataset_summary: str = ""

    def to_ai_payload(self, sample_rows: int = 2, max_columns: int = 30) -> dict[str, Any]:
        """
        Build a minimal, token-efficient payload for the AI Schema Agent.
        OPTIMIZED: Limits to top columns and minimal samples to reduce token cost.

        Args:
            sample_rows: Number of sample values per column (default 2, was 5)
            max_columns: Maximum columns to include (default 30, rest ignored)
        """
        # Limit columns if there are too many (prevents huge payloads)
        limited_columns = self.columns[:max_columns]

        return {
            "row_count": self.row_count,
            "column_count": self.column_count,
            # Track how many cols were sent
            "columns_sent": len(limited_columns),
            "columns": [
                {
                    "name": col.name,
                    "inferred_type": col.inferred_type,
                    "null_rate": round(col.null_rate, 3),
                    "unique_count": col.unique_count,
                    "sample_values": col.sample_values[:sample_rows],
                    "stats": col.stats,
                }
                for col in limited_columns
            ],
        }


def profile_dataframe(df: pd.DataFrame) -> DatasetProfile:
    """
    Run heuristic profiling on a cleaned DataFrame.
    Returns a DatasetProfile with per-column metadata.
    """
    columns = [_profile_column(df[col]) for col in df.columns]

    # Generate a basic heuristic summary
    dataset_summary = _generate_dataset_summary(df, columns)

    profile = DatasetProfile(
        row_count=len(df),
        column_count=len(df.columns),
        columns=columns,
        dataset_summary=dataset_summary,
    )
    logger.info(
        "dataframe_profiled",
        rows=profile.row_count,
        columns=profile.column_count,
        has_summary=bool(dataset_summary),
    )
    return profile


# ------------------------------------------------------------------ #
# Internal helpers
# ------------------------------------------------------------------ #


def _generate_dataset_summary(df: pd.DataFrame, columns: list[ColumnProfile]) -> str:
    """
    Generate a heuristic human-readable summary of the dataset.
    This is a fallback when AI enrichment is unavailable.
    """
    row_count = len(df)
    col_count = len(df.columns)

    # Count column types
    numeric_cols = [c for c in columns if c.inferred_type == "numeric"]
    date_cols = [c for c in columns if c.inferred_type == "date"]
    categorical_cols = [c for c in columns if c.inferred_type == "categorical"]
    text_cols = [c for c in columns if c.inferred_type == "text"]

    # Build summary string
    parts = [
        f"Dataset contains {row_count} records with {col_count} attributes.",
    ]

    if numeric_cols:
        numeric_names = ", ".join([c.name for c in numeric_cols[:3]])
        count_more = len(numeric_cols) - 3
        more_text = f" and {count_more} more" if count_more > 0 else ""
        parts.append(f"Numeric measures: {numeric_names}{more_text}.")

    if date_cols:
        date_names = ", ".join([c.name for c in date_cols[:3]])
        parts.append(f"Time dimensions: {date_names}.")

    if categorical_cols:
        cat_names = ", ".join([c.name for c in categorical_cols[:3]])
        count_more = len(categorical_cols) - 3
        more_text = f" and {count_more} more" if count_more > 0 else ""
        parts.append(f"Categorical attributes: {cat_names}{more_text}.")

    return " ".join(parts)


def _profile_column(series: pd.Series) -> ColumnProfile:
    """Infer type and compute statistics for a single column."""
    name = str(series.name)
    null_rate = series.isna().mean()
    non_null = series.dropna()
    unique_count = int(non_null.nunique())

    inferred_type = _infer_type(non_null, unique_count, len(series))
    stats = _compute_stats(non_null, inferred_type)
    suggested_role = _suggest_role(inferred_type, unique_count, len(series))
    sample_values = _safe_sample(non_null)

    return ColumnProfile(
        name=name,
        inferred_type=inferred_type,
        null_rate=float(null_rate),
        unique_count=unique_count,
        stats=stats,
        suggested_role=suggested_role,
        sample_values=sample_values,
    )


def _infer_type(
    series: pd.Series, unique_count: int, total_rows: int
) -> str:
    """
    Attempt to cast the series to numeric or date; fall back to
    categorical or text based on cardinality.
    """
    if series.empty:
        return "text"

    # Try numeric
    numeric = pd.to_numeric(series, errors="coerce")
    if numeric.notna().mean() >= TYPE_CONFIDENCE_THRESHOLD:
        return "numeric"

    # Try date (infer_datetime_format removed in pandas 3.0).
    # Suppress the dateutil fallback warning – we intentionally let pandas
    # try common formats before falling through to categorical/text.
    try:
        import warnings as _warnings
        with _warnings.catch_warnings():
            _warnings.simplefilter("ignore", UserWarning)
            parsed = pd.to_datetime(series, errors="coerce")
        if parsed.notna().mean() >= TYPE_CONFIDENCE_THRESHOLD:
            return "date"
    except Exception:
        pass

    # Categorical vs free text
    cardinality_ratio = unique_count / max(total_rows, 1)
    if cardinality_ratio <= CATEGORICAL_CARDINALITY_RATIO:
        return "categorical"

    return "text"


def _compute_stats(series: pd.Series, inferred_type: str) -> dict[str, Any]:
    """Compute type-appropriate descriptive statistics."""
    if inferred_type == "numeric":
        numeric = pd.to_numeric(series, errors="coerce").dropna()
        if numeric.empty:
            return {}
        return {
            "min": round(float(numeric.min()), 4),
            "max": round(float(numeric.max()), 4),
            "mean": round(float(numeric.mean()), 4),
            "median": round(float(numeric.median()), 4),
            "std": round(float(numeric.std()), 4),
            "sum": round(float(numeric.sum()), 4),
        }

    if inferred_type == "date":
        dates = pd.to_datetime(series, errors="coerce").dropna()
        if dates.empty:
            return {}
        return {
            "min": str(dates.min().date()),
            "max": str(dates.max().date()),
        }

    # categorical / text
    top_values = series.value_counts().head(5).to_dict()
    return {"top_values": {str(k): int(v) for k, v in top_values.items()}}


def _suggest_role(
    inferred_type: str, unique_count: int, total_rows: int
) -> str:
    """
    Heuristically assign a BI role so the dashboard knows how to use
    the column (dimension, measure, datetime, or label).
    """
    if inferred_type == "date":
        return "datetime"
    if inferred_type == "numeric":
        return "measure"
    if inferred_type == "categorical":
        return "dimension"
    # text with very low cardinality (e.g., a "name" column) → label
    if unique_count / max(total_rows, 1) > 0.50:
        return "label"
    return "dimension"


def _safe_sample(series: pd.Series, n: int = 5) -> list[Any]:
    """Return up to n non-null sample values as plain Python types."""
    sample = series.head(n).tolist()
    return [
        (
            str(v) if not isinstance(v, (int, float, bool, type(None))) else v
        )
        for v in sample
    ]
